### ISSUE TITLE
Zip metadata mismatch after fix-newlines

### ISSUE THREAD

**Issue by linsui** [obfusk/reproducible-apk-tools#19]
This happens on some apks built with build-tools 34. I find a ugly fix running fix-newlines before packageRelease. See https://gitlab.com/fdroid/fdroiddata/-/issues/3267. It seems zipalign can't reproduce the zip metadata after the fix-newlines anymore.

**Comment by obfusk** [comment]
As you're apparently unaware, AGP changed the default page size it uses for ZIP alignment last year; `fix-newlines` etc. work fine if you simply specify the right options to account for that when needed.

**Comment by linsui** [comment]
Wow, `--page-size 16` works, thanks!
