### ISSUE TITLE
call zipalign automatically

### ISSUE THREAD

**Issue by linsui** [obfusk/reproducible-apk-tools#4]
The zipalign needs to be call manully with something like `$$SDK$$/build-tools/30.0.3/zipalign`. When the build-tools is updated the path also changes. I thought it would be convenient to find sdk from environment or option and use the zipalign from the build-tools with the highest version.

**Comment by obfusk** [comment]
I would just `apt install zipalign` :)

**Comment by obfusk** [comment]
That's the `zipalign` I've used for all my testing.
